### ISSUE TITLE
Affichage incorrect du nom de certaines méthodes

### ISSUE THREAD

**Issue by crb75** [Skelly98/pstl-upmc#16]
Bug vu sur l'exemple de Bridge Hannemann_simplified:
Toutes les occurrences des méthodes print (printStar, printCapital) dans les classes n'apparaissent pas et à la place on ne voit que le type du paramètre unique des méthodes suivi d'une parenthèse fermante, ce qui donne ici "String)".  C'est peut-être simplement dû à la taille allouée à la case qui ne fait apparaître que la fin de la ligne puisque la seule autre méthode ayant un paramètre dans cette exemple est le main et elle s'affiche correctement "main(String[])" (mais elle fait peut-être l'objet d'un traitement distinct des autres méthodes dans le code). La méthode draw (sans paramètre) s'affiche quant à elle correctement "draw()".

Bug à corriger donc (en adaptant la taille de la case au contenu si le problème n'est que là).

**Comment by crb75** [comment]
Ce n'est pas un problème d'affichage car dans le xml on retrouve bien "String)" comme nom de méthode au lieu de "printX(String)" avec X="Capital" ou "Star".

**Comment by Skelly98** [comment]
Le problème vient du projet puck2, le nom de la méthode a été mal construit lors du parsing d'extendJ.
Comme nom de méthode, nous avons maintenant "printStar(String s)" par exemple.

**Comment by crb75** [comment]
Attention on veut le type des paramètres mais pas de nom de variable, donc "printStar(String)" mais pas "printStar(String s)".

**Comment by Skelly98** [comment]
Très bien, on a désormais printStar(String) et le puck2.jar de projets pstl-upmc et puck2 ont été mis à jour.
