### ISSUE TITLE
Utiliser puck 1 ou 2 pour faire le diagramme de dépendance de pstl-upmc

### ISSUE THREAD

**Issue by mikalziane** [Skelly98/pstl-upmc#3]

**Comment by mikalziane** [comment]
Pour le moment ni puck2 ni pstl-upmc ne semblent compiler avec puck1
C'est un peu dommage car extendJ est testé avec de gros outils comme Ant et Junit d'après leur page web
De plus puck2 c'est déjà essentiellement du extendJ donc ça devrait compiler avec extendJ !

**Comment by Skelly98** [comment]
Possible avec puck2 mais prend un certain temps pour s'afficher.
