### ISSUE TITLE
Le zoom n'est pas borné

### ISSUE THREAD

**Issue by pierregomez** [Skelly98/pstl-upmc#5]
En dézoomant trop, on perd le projet et on ne plus revenir dessus en zoomant, (le node est supprimé...?), pas d'autre solution que de relancer pstl-upmc (voir issue concernant la fermeture/ouverture de différents graphs)
Il faut donc limiter l'échelle de zoom

**Comment by Skelly98** [comment]
`
	public void setScaling(PSwingCanvas canvas) {
		PZoomEventHandler zoomHandler = canvas.getZoomEventHandler();
		zoomHandler.setMinScale(0.5);
		zoomHandler.setMaxScale(5);
		canvas.setZoomEventHandler(zoomHandler);
	}
	`

Le zoom est maintenant borné et peut se réaliser avec la molette de la souris
